# Generated by Django 5.0.3 on 2024-03-10 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oxytocin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
