# Generated by Django 5.0.3 on 2024-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oxytocin", "0002_notes_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
        ),
    ]
