# Generated by Django 5.0.3 on 2024-03-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oxytocin", "0003_alter_notes_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
