# Generated by Django 5.0.3 on 2024-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date_created',
        ),
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='notes',
            name='is_categorized',
            field=models.BooleanField(default=False),
        ),
    ]
