# Generated by Django 5.0.3 on 2024-03-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_notes_date_created_notes_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
